# 1: Introduction to NumPy

## Step 1: Array programming with NumPy

In [1]:
import numpy as np

### Declaring a regular Python list

In [2]:
list1 = [1, 2, 3, 4]
type(list1)

list

### Making a numpy array using Python lists

In [ ]:
array1 = np.array(list1)
array1

In [ ]:
# The type of array1 is an ndarray: an n-dimensional array
type(array1)

In [ ]:
print(array1)

### We can also use more dimensions

In [ ]:
# Declare an extra list.
list2 = [11, 22, 33, 44]
# Combine the lists into a 2-dimensional list.
lists = [list1, list2]
lists

In [ ]:
# make a 2-dimensional NumPy array
array2 = np.array(lists)
array2

### And print their shapes
We would obviously expect a (4,1) and a (4,2)... or don't we?

In [ ]:
print("Arr1: ", array1.shape)
print("Arr2: ", array2.shape)

The best way to think about NumPy arrays is that they consist of two parts, a _data buffer_ which is just a block of raw elements, and a _view_ which describes how to interpret the data buffer.

Here the shape `(4,)` means the array is indexed by a single index which runs from 0 to 3. The comma in `(4,)` is there to show that it is a tuple of integers, which is the data type of the shape attribute. Without the comma, it would simply be an integer, not a tuple of integers.

In most situations the lack of a second dimension is not a problem. If it does turn into a problem (e.g. when you are trying to take a transpose of this vector) you can just call the `reshape` function on the array to generate a new view:

In [ ]:
# Do note the double brackets, as the size is added as a tuple: (rows, columns)
array1 = array1.reshape((4,1))
array1.shape

For the above examples, we happen to know what we stored in our array, but in some cases we are not aware (like when we imported lots of data). To find out, you can call `dtype`:


In [ ]:
array2.dtype

### Initializing regularly used arrays
There are also basic ways to initialize certain arrays which are used regularly, such as:

In [3]:
# The empty array (makes an array but doesn't do any initialisation)
print("Ex1: ", np.empty(5))

# Array of 5 floating point zeros
print("Ex2: ", np.zeros(5))

# Array of 5 floating point ones
print("Ex3: ", np.ones(5))

# Array of 5 integer incrementing numbers
print("Ex4: ", np.arange(5))

# Start at 5, stop at 20, do it in steps of 2
print("Ex5: ", np.arange(5, 20, 2))

# Making the identity matrix (ones on the diagonal)
print("Ex6: ")
print(np.eye(5))

Ex1:  [2.12199579e-314 4.67296746e-307 5.15804534e-321 1.04826592e-311
 3.27034403e-317]
Ex2:  [0. 0. 0. 0. 0.]
Ex3:  [1. 1. 1. 1. 1.]
Ex4:  [0 1 2 3 4]
Ex5:  [ 5  7  9 11 13 15 17 19]
Ex6: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Mathematical operations


The power of NumPy lies in the mathematical operations you can apply on those arrays. These are applied element-wise, which means that the operation is performed on each individual element in the array. Linear Algebra operations, like matrix multiplication or dot product are performed with special NumPy functions, like `np.matmul` or `np.dot`.

In [ ]:
array3 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])
array3

In [ ]:
# Element-wise multiplication
array3 * array3

In [ ]:
# Element-wise subtraction
array3 - 5

In [ ]:
# Division
1 / array3

In [7]:
# Raising to a power
arr = np.arange(1, 10, 2)

print(arr)

print(arr ** 3)

print((arr ** 2)[2:5])

[1 3 5 7 9]
[  1  27 125 343 729]
[25 49 81]


### You can also apply functions to all elements in an array at once

The nice thing about NumPy arrays is that it allows you to manipulate the data in arrays without writing explicit loops. For instance look at the addition of all elements in an array:

In [ ]:
# Array of random numbers
a = np.random.rand(65536)

In [ ]:
#calculate the sum of the elements in array
def loopsum(a):
    sum = 0
    for i in range(len(a)):
        sum += a[i]
    return sum

In [ ]:
%timeit loopsum(a)
%timeit np.sum(a)

You can see that the numpy loop is about 350 times faster than the explicit loop version.
So be aware in this course to use built-in NumPy tools to manipulate and calculate with arrays.
Some built-in functions of NumPy can be found [here].



[here]: https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations



### Indexing Arrays

In [ ]:
array4 = np.arange(0, 10)
array4

There is a minor difference when it comes to indexing compared to Python lists: namely that a NumPy array allows an additional indexing method:

In [ ]:
list3 = [[1, 2, 3], [4, 5, 6]]
array5 = np.array(list3)

# Watch the brackets closely.
print("List: ", list3[1][2])
# Array can use two different approaches
print("Array ", array5[1, 2])
print("Array ", array5[1][2])

### Slicing arrays
Sometimes you do not want the full array, but just parts of it, we can use array slicing for this:

In [ ]:
# Show original array
print(array5)
# We want the element from the second row and third column:
print(array5[1:2,2:3])

In [ ]:
# We can also use it to set the value of multiple entries:
array4 = np.arange(0, 10)
array4[2:5] = 13
print(array4)

One important thing to note is that a slice is just another _view_ of the underlying data buffer. If you change data in the slice, you are actually changing the data in the underlying data buffer and thus in the orginal array. This is advantageous for the memory efficiency of your program, but sometimes it can cause errors when overlooked.

In [ ]:
array4 = np.arange(0, 10)
# Take a slice, consisting of the 3rd (index 2) to 6th (index 5) element.
slice_array4 = array4[2:6]
# We iterate over all values, setting them to 22
slice_array4[:] = 22
print(slice_array4)
print(array4)

To prevent this, we can also make a new copy. In this way we do not generate a view, but actually reserve new memory for the object we are making:

In [ ]:
array4 = np.arange(0, 10)
array5 = array4.copy()
print(array4)
print(array5)
array5[:] = 22
print("So did we make a copy?")
print(array4)
print(array5)
print("Seems we did.")

#### 2D array slicing

In [ ]:
array6 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print(array6)
# let's say you only want just the upper right square of 2x2 of the above matrix
# reminder: when indexing with array[start:stop]
# the element at start is *included*, while the elemnt at stop is *excluded*
array6[:2, 1:]

#### Fancy Indexing
Sometimes you don't want to retrieve every row, but perhaps skip a few entries. This is easily possible in Python. Let us assume we only want the 2nd, 3rd, 5th, and 7th row in the following example.

In [ ]:
# Below we use a list comprehension (which you should have seen in Introduction to Programming as well)
# To generate an array with 10 rows, and each column goes from 0 to 10.
array7 = np.array([[j for i in range(10)] for j in range(10)])
print(array7)
# As we start at index 0, we actually want the following rows [1, 2, 4, 6].
# Also note the double brackets below.
print("With fancy indexing:")
print(array7[[1, 2, 4, 6]])

You can do the above even in any order you wish.

In [ ]:
array7[[6, 2, 4, 1]]

### Array Transposition

In [ ]:
array8 = np.arange(40).reshape((8, 5))
array8

In [ ]:
# If you want to transpose a matrix you can do this in two ways:

print(np.transpose(array8))
# Or
print(array8.T)

### Array Processing

We can also apply functions on arrays to retrieve specific information from them, or to process the information that is contained. In this section, we will survey a number of these handy functions.

#### Numpy Where

When you want to find the location of elements in an array, you can use `np.where`. This function takes in a condition and returns the indices of the array where the condition is true.

In [ ]:
# A simple np.where example:
A = np.array([1, 2, 3, 4])
indices = np.where(A < 3)
print(indices)
print(A[indices])

#### Numpy Any & All

As shown before, we can apply a boolean operator on an array, which will return an array with boolean values:

In [ ]:
a = np.arange(9).reshape(3, 3)
bool_arr = a < 4
print(bool_arr)

Now, what if we want to return each row where any of the elements is true, we can do that with `any` in combination with `where`:

In [ ]:
# Return the indices of the rows where any column (axis=1) is true
indices = np.where(bool_arr.any(axis=1))
bool_arr[indices]
# You can see that the last row is excluded as this row doesn't contain any True values

And what if we want all elements in the row to be true? We can use `all`:

In [ ]:
# If all values are true, return true (else false)
indices = np.where(bool_arr.all(axis=1))
bool_arr[indices]
# You can see that only the first row is included as this row is the only one to contain only True values

#### Numpy Unique and `in` checking

In [ ]:
# Sometimes you just want to know all the unique values in a numpy array
# Luckily that function was already implemented for you
letters = ['A', 'B', 'C', 'D', 'D', 'A', 'E', 'F', 'G', 'H', 'Z']
np.unique(letters)

In [ ]:
# We can also easily check whether a big array exists,
# if it exists within a 1D vector.
np.in1d(['X', 'C', 'M', 'Z'], letters)

## Step 2: Practical Application of NumPy in Machine Learning

In this section, we will apply NumPy to a dataset from Scikit-learn. This will demonstrate how NumPy is used in real-world Machine Learning tasks, particularly for data representation and manipulation. 

In [13]:
import pandas as pd
titanic_data_df= pd.read_csv('data/titanic.csv')
titanic_data = titanic_data_df.to_numpy()


We can now look at the features present.

In [9]:
features = titanic_data_df.dtypes
features

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

**Question** How many features are present? (Find the length of the list above)

In [11]:
# START ANSWER
# END ANSWER
print(len(features))

12


Usually, before applying any Machine Learning algorithm we always need to inspect the data to get a better idea of its structure and the necessary preprocessing steps that need to be performed.

**Question** Print the first 10 rows of the data to understand the structure.

In [12]:
print(titanic_data[:10])

[[1 0 3 'Mr. Owen Harris' 'male' 22.0 1 0 'A/5 21171' 7.25 nan 'S']
 [2 1 1 'Mrs. John Bradley (Florence Briggs Thayer)' 'female' 38.0 1 0
  'PC 17599' 71.2833 'C85' 'C']
 [3 1 3 'Miss. Laina' 'female' 26.0 0 0 'STON/O2. 3101282' 7.925 nan 'S']
 [4 1 1 'Mrs. Jacques Heath (Lily May Peel)' 'female' 35.0 1 0 '113803'
  53.1 'C123' 'S']
 [5 0 3 'Mr. William Henry' 'male' 35.0 0 0 '373450' 8.05 nan 'S']
 [6 0 3 'Mr. James' 'male' nan 0 0 '330877' 8.4583 nan 'Q']
 [7 0 1 'Mr. Timothy J' 'male' 54.0 0 0 '17463' 51.8625 'E46' 'S']
 [8 0 3 'Master. Gosta Leonard' 'male' 2.0 3 1 '349909' 21.075 nan 'S']
 [9 1 3 'Mrs. Oscar W (Elisabeth Vilhelmina Berg)' 'female' 27.0 0 2
  '347742' 11.1333 nan 'S']
 [10 1 2 'Mrs. Nicholas (Adele Achem)' 'female' 14.0 1 0 '237736' 30.0708
  nan 'C']]


**Question** What is the shape of `titanic_data`? What does each dimension correspond to?

In [14]:
print(titanic_data.shape)

# first dimension: rows 

# second dimension: columns (attributes/features)

(891, 12)


**Question** Now, say that from the titanic data we only need the info from the first 15 passengers that tell their id, if they survived and the class in which they were traveling (three first columns). Select the desired subset from the `titanic_array` and put it into the variable `surviving_data`.

In [14]:
surviving_data = titanic_data[:15, :3]
print(titanic_data.shape)

print(surviving_data)
print('Selection correct: ', surviving_data.shape == (15,3))


(891, 12)
[[1 0 3]
 [2 1 1]
 [3 1 3]
 [4 1 1]
 [5 0 3]
 [6 0 3]
 [7 0 1]
 [8 0 3]
 [9 1 3]
 [10 1 2]
 [11 1 3]
 [12 1 1]
 [13 0 3]
 [14 0 3]
 [15 0 3]]
Selection correct:  True


**Question** The 2nd column (index 1) contains the information about the survival status of the passengers. It contains only 0s and 1s. What do these values stand for?

**Question** From the entire data, can you extract the information of all the passengers that survived? Hint: Use `np.where` to get the indices of the surviving passengers.

In [16]:
survived_idx = np.where(titanic_data[:, 1] == 1)[0]
titanic_survived = titanic_data[survived_idx]
print(titanic_survived)

[[2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 [4 1 1 ... 53.1 'C123' 'S']
 ...
 [881 1 2 ... 26.0 nan 'S']
 [888 1 1 ... 30.0 'B42' 'S']
 [890 1 1 ... 30.0 'C148' 'C']]


## Step 3: Practice Numpy


These are optional exercises, but highly recommended to get you familiar with some basic NumPy operations and tricks. If you get stuck, try to dive into the Numpy documentation first, to see if it can be of help as not all functions you need for the exercises are explained above.

### Array Calculations and Array Indexing
In all exercises below you are not allowed to use a loop.

In [ ]:
# Given two arrays A and B each of the same size calculate their sum (elementwise) and their product (elementwise).
A = np.arange(5)
B = np.arange(5, 10)

def sum_arrays(A, B):
    result = None
    # START ANSWER
    result = A + B
    # END ANSWER
    return result

def multiply_arrays(A, B):
    result = None
    # START ANSWER
    result = A * B
    # END ANSWER
    return result

sum_AB = sum_arrays(A, B)
assert (sum_AB == np.array([ 5,  7,  9, 11, 13])).all()
mult_AB = multiply_arrays(A, B)
assert (mult_AB == np.array([ 0,  6, 14, 24, 36])).all()

sum_AB, mult_AB

(array([ 5,  7,  9, 11, 13]), array([ 0,  6, 14, 24, 36]))

In [3]:
# Given an array A with shape (128,) calculate the mean of the elements at even indexes.
A = np.arange(128)

def mean_even_idx(A):
    result = None
    # START ANSWER
    result = np.mean(A[::2])
    # END ANSWER
    return result

mean_A = mean_even_idx(A)
assert mean_A == 63.0

mean_A

np.float64(63.0)

In [4]:
# Given an array A with shape (N,) make an array with all elements of A in reverse order
# and return as a matrix of size (N, 1).
A = np.arange(6)

def reverse(A):
    result = None
    # START ANSWER
    result = A[::-1].reshape(-1, 1)
    # END ANSWER
    return result

rev = reverse(A)
assert (rev == np.array([[5],[4],[3],[2],[1],[0]])).all()
rev

array([[5],
       [4],
       [3],
       [2],
       [1],
       [0]])

#### Two dimensional data arrays
In this course you will be working a lot with matrices and vectors. The following exercises will let you practice with those.

Given is data matrix X with shape (m, n)

In [5]:
m = n = 5
X = np.arange(m * n).reshape(m, n)

print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
# Select the j-th column from the matrix X. What happens if you use X[j]? Is this correct?
j = 3
column = None
# START ANSWER
column = X[:, j]
# X[j] selects row j, not column j.
# END ANSWER

assert (column == np.array([ 3,  8, 13, 18, 23])).all()
column

array([ 3,  8, 13, 18, 23])

In [7]:
# Given an ndarray X with shape (m,n), calculate the mean of each column.
# Try doing this without using np.mean or loops.
# Hint: try to sum up the entries and dividing them by the number of elements

means = 0
# START ANSWER
means = np.sum(X, axis=0) / X.shape[0]
# END ANSWER

assert (means == np.array([10., 11., 12., 13., 14.])).all()
means

array([10., 11., 12., 13., 14.])

In [8]:
# Now subtract the mean vector you just calculated from all the rows in your matrix leading to the 
# data matrix X_0. Yes this can be done without a loop! Hint: look at array broadcasting.

X_0 = None
# START ANSWER
X_0 = X - means
# END ANSWER

assert (X_0 == np.array([[-10., -10., -10., -10., -10.],
                         [ -5.,  -5.,  -5.,  -5.,  -5.],
                         [  0.,   0.,   0.,   0.,   0.],
                         [  5.,   5.,   5.,   5.,   5.],
                         [ 10.,  10.,  10.,  10.,  10.]])
       ).all()
X_0

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [9]:
# Given column j, find the largest element and return the entire row of this element.
# Hint: look at the function np.argmax for this.
X = np.random.rand(m, n)
j = 3

# START ANSWER
max_row = X[np.argmax(X[:, j]), :]
assert max_row[j] == np.max(X[:, j])
# END ANSWER

# Please inspect visually whether your code returns the right row
X, max_row

(array([[0.30382533, 0.00985605, 0.14000561, 0.15371613, 0.96404569],
        [0.84529628, 0.17869341, 0.2517984 , 0.05467799, 0.39100931],
        [0.58391067, 0.08666492, 0.50044123, 0.42704566, 0.01359129],
        [0.98205572, 0.21717414, 0.88920221, 0.56810045, 0.65554001],
        [0.67410756, 0.74698138, 0.98959575, 0.53390334, 0.30210695]]),
 array([0.98205572, 0.21717414, 0.88920221, 0.56810045, 0.65554001]))

#### Advanced Linear Algebra

In Python 3, the @ operator is introduced for matrix multiplication. Let A be an array of shape (m, n) and 
let B be an array of shape (n, k) then we can write A @ B for the matrix multiplication of A and B. 

Note that there is conceptual difference between a 1 dimensional array V of size (N,) 
and a vector V as we know it from linear algebra. In linear algebra, a vector with $N$ elements has dimensions $N \times 1$. 
A ‘vector’ V as a numpy array has shape (N,).




In [10]:
# Calculate the inner product of two vector v and w both of shape (N,).
# Validate your result by computing the dot product using multiply and sum operations.
v = np.arange(5)
w = np.arange(5, 10)

# START ANSWER
inner_product = v @ w
assert inner_product == np.sum(v * w)
inner_product
# END ANSWER

np.int64(80)

In [11]:
# Calculate the product of a matrix A of shape (M,N) with a vector v of shape (N,).
m = n = 5
X = np.arange(m * n).reshape(m, n)
v = np.arange(n)

product = None
# START ANSWER
product = X @ v
# END ANSWER

assert (product == np.array([ 30,  80, 130, 180, 230])).all()
product        

array([ 30,  80, 130, 180, 230])